### ISSUE TITLE
Support top-level return

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/babel-plugin-transform-commonjs#1]
Some modules do early return when working with something like the cluster module. Since ES Modules do not have a wrapping function scope, this is an invalid transformation. We should search for all top-level returns and either remove everything in the body past them or wrap with an else block.

``` javascript
const { isMaster, fork } = require('cluster');

if (isMaster) {
  fork();
  return;
}

console.log('forked', process.pid);
```

Should be converted into:

``` javascript
import { isMaster, fork } from 'cluster';

if (isMaster) {
  fork();
}
else {
  console.log('forked', process.pid);
}
```

Can anyone think of a better way of handling this?

**Comment by tbranyen** [comment]
Another thought that came to me is whenever a top level return is encountered, we automatically wrap the CJS module body in a function to avoid any kind of code rewriting. I'm pretty sure we'd want to use a context binding IIFE rather than generating a brand new function scope.

The ESM `this` should match the CommonJS `this`.

Something like:

``` js
import { isMaster, fork } from 'cluster';

(() => {
  if (isMaster) {
    fork();
    return;
  }

  console.log('forked', process.pid);
})();
```

**Comment by Rich-Harris** [comment]
rollup-plugin-commonjs takes the second route — it tries to convert the module to idiomatic ESM, but if it fails (because of an early return, or `exports` being used in a way that doesn't have an ESM equivalent, etc) then it wraps it using an internal helper called `createCommonjsModule`:

```js
import require$$1 from 'x';

var foo = createCommonjsModule(function (module, exports) {
  // original body here, with `require('x')` replaced with `require$$1` etc
});

export default foo;
```

Not perfect for every case (you can do some filthy stuff with CommonJS that defeats this kind of transformation, e.g. inline conditional requires and cyclical nonsense) but good enough for the vast majority.

**Comment by tbranyen** [comment]
I have a solution that looks to work, but will need more tests and refinement. Closing for now.
